#platform :ios, '10.0'

target 'CreekSDK_Example' do
  
  use_frameworks!
  pod 'CreekSDK', :path => '../'
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'Toast-Swift'
  pod 'ZIPFoundation'
  pod "ESTabBarController-swift"
  
  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                 end
            end
     end
  end

end
