#platform :ios, '10.0'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'CreekSDK_Example' do
  
  use_frameworks!
  pod 'CreekSDK', :path => '../'
  pod 'SnapKit'
  pod 'MBProgressHUD'
  pod 'Toast-Swift'
  pod 'ZIPFoundation'
#  pod "ESTabBarController-swift"
  pod 'CropViewController'
  pod 'TZImagePickerController'
  pod 'IQKeyboardManagerSwift'
  
  post_install do |installer|
#
#    installer.pods_project.targets.each do |target|
#             target.build_configurations.each do |config|
#                  # You can remove unused permissions here
#                  # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
#                  # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
#                  config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
#                    '$(inherited)',
#                    ## dart: PermissionGroup.contacts
#                    'PERMISSION_CONTACTS=1',
#                  ]
#         
#             end
#           end
    
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                 end
            end
     end
  end

end
