// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: appTable.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct protocol_app_function_table: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///消息快捷回复
  public var callMsgReply: Bool = false

  ///文件传输通知结束
  public var logTranNotifyEnd: Bool = false

  ///gps芯与物cc1165w 版本号2支持7天星历
  public var gpsCc1165WVersion: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension protocol_app_function_table: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_app_function_table"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "call_msg_reply"),
    2: .standard(proto: "log_tran_notify_end"),
    3: .standard(proto: "gps_cc1165w_version"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.callMsgReply) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.logTranNotifyEnd) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.gpsCc1165WVersion) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.callMsgReply != false {
      try visitor.visitSingularBoolField(value: self.callMsgReply, fieldNumber: 1)
    }
    if self.logTranNotifyEnd != false {
      try visitor.visitSingularBoolField(value: self.logTranNotifyEnd, fieldNumber: 2)
    }
    if self.gpsCc1165WVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.gpsCc1165WVersion, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_app_function_table, rhs: protocol_app_function_table) -> Bool {
    if lhs.callMsgReply != rhs.callMsgReply {return false}
    if lhs.logTranNotifyEnd != rhs.logTranNotifyEnd {return false}
    if lhs.gpsCc1165WVersion != rhs.gpsCc1165WVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
