// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: gomoreFitnessLevel.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct gomore_fitness_level_day: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var year: UInt32 = 0

  public var month: UInt32 = 0

  public var day: UInt32 = 0

  public var levelItem: [gomore_fitness_level_item] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct gomore_fitness_level_item: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var hour: UInt32 = 0

  public var minute: UInt32 = 0

  public var second: UInt32 = 0

  /// 整体耐力水平（体能等级），10.0~80.0，×10
  public var fitnessLevel: UInt32 = 0

  /// 有氧耐力水平，×10
  public var aerobicEnduranceLevel: UInt32 = 0

  /// 无氧耐力水平，×10
  public var anaerobicEnduranceLevel: UInt32 = 0

  /// 爆发力能力，×10
  public var explosivePowerAbility: UInt32 = 0

  /// 无氧能力，×10
  public var anaerobicCapacity: UInt32 = 0

  /// 有氧冲刺能力，×10
  public var aerobicSprintAbility: UInt32 = 0

  /// 有氧能力，×10
  public var aerobicCapacity: UInt32 = 0

  /// 耐力能力，×10
  public var enduranceAbility: UInt32 = 0

  /// 超耐力能力，×10
  public var ultraEnduranceAbility: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct protocol_gomore_fitness_level_operate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// INQUIRE=1 查询
  public var operate: operate_type = .invalid

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct protocol_gomore_fitness_level_inquire_reply: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///1bytes 操作类型 0：无效操作 1：查询 2：设置
  public var operate: operate_type = .invalid

  public var levelItem: [gomore_fitness_level_day] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension gomore_fitness_level_day: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "gomore_fitness_level_day"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "year"),
    2: .same(proto: "month"),
    3: .same(proto: "day"),
    4: .standard(proto: "level_item"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.year) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.month) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.day) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.levelItem) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.year != 0 {
      try visitor.visitSingularUInt32Field(value: self.year, fieldNumber: 1)
    }
    if self.month != 0 {
      try visitor.visitSingularUInt32Field(value: self.month, fieldNumber: 2)
    }
    if self.day != 0 {
      try visitor.visitSingularUInt32Field(value: self.day, fieldNumber: 3)
    }
    if !self.levelItem.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.levelItem, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: gomore_fitness_level_day, rhs: gomore_fitness_level_day) -> Bool {
    if lhs.year != rhs.year {return false}
    if lhs.month != rhs.month {return false}
    if lhs.day != rhs.day {return false}
    if lhs.levelItem != rhs.levelItem {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension gomore_fitness_level_item: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "gomore_fitness_level_item"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "hour"),
    2: .same(proto: "minute"),
    3: .same(proto: "second"),
    4: .same(proto: "fitnessLevel"),
    5: .same(proto: "aerobicEnduranceLevel"),
    6: .same(proto: "anaerobicEnduranceLevel"),
    7: .same(proto: "explosivePowerAbility"),
    8: .same(proto: "anaerobicCapacity"),
    9: .same(proto: "aerobicSprintAbility"),
    10: .same(proto: "aerobicCapacity"),
    11: .same(proto: "enduranceAbility"),
    12: .same(proto: "ultraEnduranceAbility"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.hour) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.minute) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.second) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.fitnessLevel) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.aerobicEnduranceLevel) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.anaerobicEnduranceLevel) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.explosivePowerAbility) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.anaerobicCapacity) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.aerobicSprintAbility) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.aerobicCapacity) }()
      case 11: try { try decoder.decodeSingularUInt32Field(value: &self.enduranceAbility) }()
      case 12: try { try decoder.decodeSingularUInt32Field(value: &self.ultraEnduranceAbility) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.hour != 0 {
      try visitor.visitSingularUInt32Field(value: self.hour, fieldNumber: 1)
    }
    if self.minute != 0 {
      try visitor.visitSingularUInt32Field(value: self.minute, fieldNumber: 2)
    }
    if self.second != 0 {
      try visitor.visitSingularUInt32Field(value: self.second, fieldNumber: 3)
    }
    if self.fitnessLevel != 0 {
      try visitor.visitSingularUInt32Field(value: self.fitnessLevel, fieldNumber: 4)
    }
    if self.aerobicEnduranceLevel != 0 {
      try visitor.visitSingularUInt32Field(value: self.aerobicEnduranceLevel, fieldNumber: 5)
    }
    if self.anaerobicEnduranceLevel != 0 {
      try visitor.visitSingularUInt32Field(value: self.anaerobicEnduranceLevel, fieldNumber: 6)
    }
    if self.explosivePowerAbility != 0 {
      try visitor.visitSingularUInt32Field(value: self.explosivePowerAbility, fieldNumber: 7)
    }
    if self.anaerobicCapacity != 0 {
      try visitor.visitSingularUInt32Field(value: self.anaerobicCapacity, fieldNumber: 8)
    }
    if self.aerobicSprintAbility != 0 {
      try visitor.visitSingularUInt32Field(value: self.aerobicSprintAbility, fieldNumber: 9)
    }
    if self.aerobicCapacity != 0 {
      try visitor.visitSingularUInt32Field(value: self.aerobicCapacity, fieldNumber: 10)
    }
    if self.enduranceAbility != 0 {
      try visitor.visitSingularUInt32Field(value: self.enduranceAbility, fieldNumber: 11)
    }
    if self.ultraEnduranceAbility != 0 {
      try visitor.visitSingularUInt32Field(value: self.ultraEnduranceAbility, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: gomore_fitness_level_item, rhs: gomore_fitness_level_item) -> Bool {
    if lhs.hour != rhs.hour {return false}
    if lhs.minute != rhs.minute {return false}
    if lhs.second != rhs.second {return false}
    if lhs.fitnessLevel != rhs.fitnessLevel {return false}
    if lhs.aerobicEnduranceLevel != rhs.aerobicEnduranceLevel {return false}
    if lhs.anaerobicEnduranceLevel != rhs.anaerobicEnduranceLevel {return false}
    if lhs.explosivePowerAbility != rhs.explosivePowerAbility {return false}
    if lhs.anaerobicCapacity != rhs.anaerobicCapacity {return false}
    if lhs.aerobicSprintAbility != rhs.aerobicSprintAbility {return false}
    if lhs.aerobicCapacity != rhs.aerobicCapacity {return false}
    if lhs.enduranceAbility != rhs.enduranceAbility {return false}
    if lhs.ultraEnduranceAbility != rhs.ultraEnduranceAbility {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension protocol_gomore_fitness_level_operate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_gomore_fitness_level_operate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "operate"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.operate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.operate != .invalid {
      try visitor.visitSingularEnumField(value: self.operate, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_gomore_fitness_level_operate, rhs: protocol_gomore_fitness_level_operate) -> Bool {
    if lhs.operate != rhs.operate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension protocol_gomore_fitness_level_inquire_reply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_gomore_fitness_level_inquire_reply"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "operate"),
    3: .standard(proto: "level_item"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.operate) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.levelItem) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.operate != .invalid {
      try visitor.visitSingularEnumField(value: self.operate, fieldNumber: 1)
    }
    if !self.levelItem.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.levelItem, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_gomore_fitness_level_inquire_reply, rhs: protocol_gomore_fitness_level_inquire_reply) -> Bool {
    if lhs.operate != rhs.operate {return false}
    if lhs.levelItem != rhs.levelItem {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
