// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: healthRealtime.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct protocol_health_realtime_monitor_operate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///1bytes 功能表
  public var funcTable: UInt32 = 0

  ///开始监控
  public var operate: health_realtime_operate_type = .healthStart

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 实时健康数据监听
public struct protocol_health_realtime_data_operate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 传输方向（手表发起或App发起）
  public var tranType: tran_direction_type = .watchTran

  ///心率数据
  public var hrValue: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct protocol_health_realtime_operate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///1bytes 操作类型 0：无效操作 1：查询 2：设置
  public var operate: operate_type = .invalid

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct protocol_health_realtime_inquire_reply: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///1bytes 操作类型 0：无效操作 1：查询 2：设置
  public var operate: operate_type = .invalid

  ///总步数
  public var totalStep: UInt32 = 0

  ///总锻炼时长 单位分钟
  public var totolExerciseMin: UInt32 = 0

  ///活动卡路里
  public var totolActivityCalories: UInt32 = 0

  ///距离，单位米
  public var totolDistance: UInt32 = 0

  ///血氧
  public var spo2Value: UInt32 = 0

  ///心率
  public var hrvValue: UInt32 = 0

  ///压力值
  public var stressValue: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension protocol_health_realtime_monitor_operate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_health_realtime_monitor_operate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "func_table"),
    2: .same(proto: "operate"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.funcTable) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.operate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.funcTable != 0 {
      try visitor.visitSingularUInt32Field(value: self.funcTable, fieldNumber: 1)
    }
    if self.operate != .healthStart {
      try visitor.visitSingularEnumField(value: self.operate, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_health_realtime_monitor_operate, rhs: protocol_health_realtime_monitor_operate) -> Bool {
    if lhs.funcTable != rhs.funcTable {return false}
    if lhs.operate != rhs.operate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension protocol_health_realtime_data_operate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_health_realtime_data_operate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "tran_type"),
    2: .standard(proto: "hr_value"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.tranType) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.hrValue) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tranType != .watchTran {
      try visitor.visitSingularEnumField(value: self.tranType, fieldNumber: 1)
    }
    if self.hrValue != 0 {
      try visitor.visitSingularUInt32Field(value: self.hrValue, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_health_realtime_data_operate, rhs: protocol_health_realtime_data_operate) -> Bool {
    if lhs.tranType != rhs.tranType {return false}
    if lhs.hrValue != rhs.hrValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension protocol_health_realtime_operate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_health_realtime_operate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "operate"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.operate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.operate != .invalid {
      try visitor.visitSingularEnumField(value: self.operate, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_health_realtime_operate, rhs: protocol_health_realtime_operate) -> Bool {
    if lhs.operate != rhs.operate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension protocol_health_realtime_inquire_reply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_health_realtime_inquire_reply"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "operate"),
    2: .standard(proto: "total_step"),
    3: .standard(proto: "totol_exercise_min"),
    4: .standard(proto: "totol_activity_calories"),
    5: .standard(proto: "totol_distance"),
    6: .standard(proto: "spo2_value"),
    7: .standard(proto: "hrv_value"),
    8: .standard(proto: "stress_value"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.operate) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.totalStep) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.totolExerciseMin) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.totolActivityCalories) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.totolDistance) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.spo2Value) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.hrvValue) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.stressValue) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.operate != .invalid {
      try visitor.visitSingularEnumField(value: self.operate, fieldNumber: 1)
    }
    if self.totalStep != 0 {
      try visitor.visitSingularUInt32Field(value: self.totalStep, fieldNumber: 2)
    }
    if self.totolExerciseMin != 0 {
      try visitor.visitSingularUInt32Field(value: self.totolExerciseMin, fieldNumber: 3)
    }
    if self.totolActivityCalories != 0 {
      try visitor.visitSingularUInt32Field(value: self.totolActivityCalories, fieldNumber: 4)
    }
    if self.totolDistance != 0 {
      try visitor.visitSingularUInt32Field(value: self.totolDistance, fieldNumber: 5)
    }
    if self.spo2Value != 0 {
      try visitor.visitSingularUInt32Field(value: self.spo2Value, fieldNumber: 6)
    }
    if self.hrvValue != 0 {
      try visitor.visitSingularUInt32Field(value: self.hrvValue, fieldNumber: 7)
    }
    if self.stressValue != 0 {
      try visitor.visitSingularUInt32Field(value: self.stressValue, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_health_realtime_inquire_reply, rhs: protocol_health_realtime_inquire_reply) -> Bool {
    if lhs.operate != rhs.operate {return false}
    if lhs.totalStep != rhs.totalStep {return false}
    if lhs.totolExerciseMin != rhs.totolExerciseMin {return false}
    if lhs.totolActivityCalories != rhs.totolActivityCalories {return false}
    if lhs.totolDistance != rhs.totolDistance {return false}
    if lhs.spo2Value != rhs.spo2Value {return false}
    if lhs.hrvValue != rhs.hrvValue {return false}
    if lhs.stressValue != rhs.stressValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
