// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: hotKey.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct protocol_button_crown_operate {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.
    
    ///1bytes operation type 0: invalid operation 1: query 2: setting
    public var operate: operate_type = .invalid
    
    ///1bytes long press for 2s to enter
    public var longType: long_2s_press_type = .pressTypeNull
    
    ///1bytes Set whether the button pause function is required during exercise
    public  var pauseWorkout: Bool = false
    
    public var unknownFields = SwiftProtobuf.UnknownStorage()
    
    public init() {}
}

public struct protocol_button_crown_inquire_reply {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.
    
    ///1bytes operation type 0: invalid operation 1: query 2: setting
    public var operate: operate_type = .invalid
    
    ///1bytes long press for 2s to enter
    public var longType: long_2s_press_type = .pressTypeNull
    
    ///1bytes Set whether the button pause function is required during exercise
    public var pauseWorkout: Bool = false
    
    public var unknownFields = SwiftProtobuf.UnknownStorage()
    
    public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension protocol_button_crown_operate: @unchecked Sendable {}
extension protocol_button_crown_inquire_reply: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension protocol_button_crown_operate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = "protocol_button_crown_operate"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "operate"),
        2: .standard(proto: "long_type"),
        3: .standard(proto: "pause_workout"),
    ]
    
    mutating public func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeSingularEnumField(value: &self.operate) }()
            case 2: try { try decoder.decodeSingularEnumField(value: &self.longType) }()
            case 3: try { try decoder.decodeSingularBoolField(value: &self.pauseWorkout) }()
            default: break
            }
        }
    }
    
    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if self.operate != .invalid {
            try visitor.visitSingularEnumField(value: self.operate, fieldNumber: 1)
        }
        if self.longType != .pressTypeNull {
            try visitor.visitSingularEnumField(value: self.longType, fieldNumber: 2)
        }
        if self.pauseWorkout != false {
            try visitor.visitSingularBoolField(value: self.pauseWorkout, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }
    
    public static func ==(lhs: protocol_button_crown_operate, rhs: protocol_button_crown_operate) -> Bool {
        if lhs.operate != rhs.operate {return false}
        if lhs.longType != rhs.longType {return false}
        if lhs.pauseWorkout != rhs.pauseWorkout {return false}
        if lhs.unknownFields != rhs.unknownFields {return false}
        return true
    }
}

extension protocol_button_crown_inquire_reply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = "protocol_button_crown_inquire_reply"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "operate"),
        2: .standard(proto: "long_type"),
        3: .standard(proto: "pause_workout"),
    ]
    
    mutating public func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeSingularEnumField(value: &self.operate) }()
            case 2: try { try decoder.decodeSingularEnumField(value: &self.longType) }()
            case 3: try { try decoder.decodeSingularBoolField(value: &self.pauseWorkout) }()
            default: break
            }
        }
    }
    
    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if self.operate != .invalid {
            try visitor.visitSingularEnumField(value: self.operate, fieldNumber: 1)
        }
        if self.longType != .pressTypeNull {
            try visitor.visitSingularEnumField(value: self.longType, fieldNumber: 2)
        }
        if self.pauseWorkout != false {
            try visitor.visitSingularBoolField(value: self.pauseWorkout, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }
    
    public static func ==(lhs: protocol_button_crown_inquire_reply, rhs: protocol_button_crown_inquire_reply) -> Bool {
        if lhs.operate != rhs.operate {return false}
        if lhs.longType != rhs.longType {return false}
        if lhs.pauseWorkout != rhs.pauseWorkout {return false}
        if lhs.unknownFields != rhs.unknownFields {return false}
        return true
    }
}
