// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: onekeyMeasure.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct protocol_onekey_measure_operate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///传输方向
  public var tranType: tran_direction_type = .watchTran

  ///测量操作
  public var measureType: health_measure_type = .healthMeasureStart

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct protocol_onekey_measure_inquire_reply: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///传输方向
  public var tranType: tran_direction_type = .watchTran

  ///测量操作
  public var measureType: health_measure_type = .healthMeasureStart

  ///测量状态
  public var measureStatus: health_measure_status = .healthStatusMeasuring

  ///异常状态
  public var abnormalStatus: health_abnormal_status = .healthAbnormalNone

  ///心率测量值
  public var heartrateValue: UInt32 = 0

  ///血氧测量值
  public var spo2Value: UInt32 = 0

  ///HRV测量值
  public var hrvValue: UInt32 = 0

  ///压力测量值
  public var stressValue: UInt32 = 0

  ///呼吸率测量值
  public var breathtrateValue: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension protocol_onekey_measure_operate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_onekey_measure_operate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "tran_type"),
    2: .standard(proto: "measure_type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.tranType) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.measureType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tranType != .watchTran {
      try visitor.visitSingularEnumField(value: self.tranType, fieldNumber: 1)
    }
    if self.measureType != .healthMeasureStart {
      try visitor.visitSingularEnumField(value: self.measureType, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_onekey_measure_operate, rhs: protocol_onekey_measure_operate) -> Bool {
    if lhs.tranType != rhs.tranType {return false}
    if lhs.measureType != rhs.measureType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension protocol_onekey_measure_inquire_reply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_onekey_measure_inquire_reply"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "tran_type"),
    2: .standard(proto: "measure_type"),
    3: .standard(proto: "measure_status"),
    4: .standard(proto: "abnormal_status"),
    5: .standard(proto: "heartrate_value"),
    6: .standard(proto: "spo2_value"),
    7: .standard(proto: "hrv_value"),
    8: .standard(proto: "stress_value"),
    9: .standard(proto: "breathtrate_value"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.tranType) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.measureType) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.measureStatus) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.abnormalStatus) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.heartrateValue) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.spo2Value) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.hrvValue) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.stressValue) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.breathtrateValue) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tranType != .watchTran {
      try visitor.visitSingularEnumField(value: self.tranType, fieldNumber: 1)
    }
    if self.measureType != .healthMeasureStart {
      try visitor.visitSingularEnumField(value: self.measureType, fieldNumber: 2)
    }
    if self.measureStatus != .healthStatusMeasuring {
      try visitor.visitSingularEnumField(value: self.measureStatus, fieldNumber: 3)
    }
    if self.abnormalStatus != .healthAbnormalNone {
      try visitor.visitSingularEnumField(value: self.abnormalStatus, fieldNumber: 4)
    }
    if self.heartrateValue != 0 {
      try visitor.visitSingularUInt32Field(value: self.heartrateValue, fieldNumber: 5)
    }
    if self.spo2Value != 0 {
      try visitor.visitSingularUInt32Field(value: self.spo2Value, fieldNumber: 6)
    }
    if self.hrvValue != 0 {
      try visitor.visitSingularUInt32Field(value: self.hrvValue, fieldNumber: 7)
    }
    if self.stressValue != 0 {
      try visitor.visitSingularUInt32Field(value: self.stressValue, fieldNumber: 8)
    }
    if self.breathtrateValue != 0 {
      try visitor.visitSingularUInt32Field(value: self.breathtrateValue, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_onekey_measure_inquire_reply, rhs: protocol_onekey_measure_inquire_reply) -> Bool {
    if lhs.tranType != rhs.tranType {return false}
    if lhs.measureType != rhs.measureType {return false}
    if lhs.measureStatus != rhs.measureStatus {return false}
    if lhs.abnormalStatus != rhs.abnormalStatus {return false}
    if lhs.heartrateValue != rhs.heartrateValue {return false}
    if lhs.spo2Value != rhs.spo2Value {return false}
    if lhs.hrvValue != rhs.hrvValue {return false}
    if lhs.stressValue != rhs.stressValue {return false}
    if lhs.breathtrateValue != rhs.breathtrateValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
