// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: protocol_fifa.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct match_info: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 比赛唯一标识，如 "worldcup2026_arg_bra_001"
  public var matchID: Data = Data()

  /// 球队 A 信息（左侧/主队）
  public var teamAFifa3Code: Data = Data()

  /// 球队 B 信息（右侧/客队）
  public var teamBFifa3Code: Data = Data()

  /// 当前比赛状态，决定界面标题与卡片样式
  public var status: match_status = .unspecified

  /// 球队 A 当前比分
  public var scoreA: Int32 = 0

  /// 球队 B 当前比分
  public var scoreB: Int32 = 0

  /// 开赛时间戳（Unix 秒），手表端本地格式化为 "MM/DD HH:MM"
  public var startTime: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct match_list: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 比赛数组，按优先级与时间排序
  public var matches: [match_info] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct goal_event: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 关联比赛 ID，用于点击通知跳转对应比赛卡片
  public var matchID: Data = Data()

  /// 进球队员中文名，单行滚动显示
  public var playerNameCn: Data = Data()

  /// 进球队员英文名，备用显示
  public var playerNameEn: Data = Data()

  /// 进球发生时间，从比赛开始起的偏移秒数，如 53'23" = 3203 秒，最大值 59999（对应 999'59"），手表端格式化为 "MM'SS\""
  public var matchTime: UInt32 = 0

  /// 进球类型，决定底部是否展示备注
  public var goalType: goal_type = .unspecified

  /// 进球球队 FIFA3 代码，手表端映射国旗图片
  public var scoringTeamFifa3: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct fifa_message: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 消息类型，决定 payload 解析方式
  public var type: msg_type = .msgUnspecified

  /// 全量比赛列表，覆盖手表端缓存
  public var matchList: match_list {
    get {return _matchList ?? match_list()}
    set {_matchList = newValue}
  }
  /// Returns true if `matchList` has been explicitly set.
  public var hasMatchList: Bool {return self._matchList != nil}
  /// Clears the value of `matchList`. Subsequent reads from it will return its default value.
  public mutating func clearMatchList() {self._matchList = nil}

  /// 单个进球事件，独立推送
  public var goalEvent: goal_event {
    get {return _goalEvent ?? goal_event()}
    set {_goalEvent = newValue}
  }
  /// Returns true if `goalEvent` has been explicitly set.
  public var hasGoalEvent: Bool {return self._goalEvent != nil}
  /// Clears the value of `goalEvent`. Subsequent reads from it will return its default value.
  public mutating func clearGoalEvent() {self._goalEvent = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _matchList: match_list? = nil
  fileprivate var _goalEvent: goal_event? = nil
}

public struct protocol_fifa_operate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///1bytes 操作类型 0：无效操作 1：查询 2：设置
  public var operate: operate_type = .invalid

  public var fifaMsg: [fifa_message] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension match_info: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "match_info"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "match_id"),
    2: .standard(proto: "team_a_fifa3_code"),
    3: .standard(proto: "team_b_fifa3_code"),
    4: .same(proto: "status"),
    5: .standard(proto: "score_a"),
    6: .standard(proto: "score_b"),
    7: .standard(proto: "start_time"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.matchID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.teamAFifa3Code) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.teamBFifa3Code) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.scoreA) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.scoreB) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.startTime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.matchID.isEmpty {
      try visitor.visitSingularBytesField(value: self.matchID, fieldNumber: 1)
    }
    if !self.teamAFifa3Code.isEmpty {
      try visitor.visitSingularBytesField(value: self.teamAFifa3Code, fieldNumber: 2)
    }
    if !self.teamBFifa3Code.isEmpty {
      try visitor.visitSingularBytesField(value: self.teamBFifa3Code, fieldNumber: 3)
    }
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 4)
    }
    if self.scoreA != 0 {
      try visitor.visitSingularInt32Field(value: self.scoreA, fieldNumber: 5)
    }
    if self.scoreB != 0 {
      try visitor.visitSingularInt32Field(value: self.scoreB, fieldNumber: 6)
    }
    if self.startTime != 0 {
      try visitor.visitSingularUInt32Field(value: self.startTime, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: match_info, rhs: match_info) -> Bool {
    if lhs.matchID != rhs.matchID {return false}
    if lhs.teamAFifa3Code != rhs.teamAFifa3Code {return false}
    if lhs.teamBFifa3Code != rhs.teamBFifa3Code {return false}
    if lhs.status != rhs.status {return false}
    if lhs.scoreA != rhs.scoreA {return false}
    if lhs.scoreB != rhs.scoreB {return false}
    if lhs.startTime != rhs.startTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension match_list: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "match_list"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "matches"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.matches) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.matches.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.matches, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: match_list, rhs: match_list) -> Bool {
    if lhs.matches != rhs.matches {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension goal_event: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "goal_event"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "match_id"),
    2: .standard(proto: "player_name_cn"),
    3: .standard(proto: "player_name_en"),
    4: .standard(proto: "match_time"),
    5: .standard(proto: "goal_type"),
    6: .standard(proto: "scoring_team_fifa3"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.matchID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.playerNameCn) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.playerNameEn) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.matchTime) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.goalType) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.scoringTeamFifa3) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.matchID.isEmpty {
      try visitor.visitSingularBytesField(value: self.matchID, fieldNumber: 1)
    }
    if !self.playerNameCn.isEmpty {
      try visitor.visitSingularBytesField(value: self.playerNameCn, fieldNumber: 2)
    }
    if !self.playerNameEn.isEmpty {
      try visitor.visitSingularBytesField(value: self.playerNameEn, fieldNumber: 3)
    }
    if self.matchTime != 0 {
      try visitor.visitSingularUInt32Field(value: self.matchTime, fieldNumber: 4)
    }
    if self.goalType != .unspecified {
      try visitor.visitSingularEnumField(value: self.goalType, fieldNumber: 5)
    }
    if !self.scoringTeamFifa3.isEmpty {
      try visitor.visitSingularBytesField(value: self.scoringTeamFifa3, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: goal_event, rhs: goal_event) -> Bool {
    if lhs.matchID != rhs.matchID {return false}
    if lhs.playerNameCn != rhs.playerNameCn {return false}
    if lhs.playerNameEn != rhs.playerNameEn {return false}
    if lhs.matchTime != rhs.matchTime {return false}
    if lhs.goalType != rhs.goalType {return false}
    if lhs.scoringTeamFifa3 != rhs.scoringTeamFifa3 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension fifa_message: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "fifa_message"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .standard(proto: "match_list"),
    3: .standard(proto: "goal_event"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._matchList) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._goalEvent) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.type != .msgUnspecified {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    try { if let v = self._matchList {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._goalEvent {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: fifa_message, rhs: fifa_message) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs._matchList != rhs._matchList {return false}
    if lhs._goalEvent != rhs._goalEvent {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension protocol_fifa_operate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_fifa_operate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "operate"),
    2: .standard(proto: "fifa_msg"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.operate) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.fifaMsg) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.operate != .invalid {
      try visitor.visitSingularEnumField(value: self.operate, fieldNumber: 1)
    }
    if !self.fifaMsg.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fifaMsg, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_fifa_operate, rhs: protocol_fifa_operate) -> Bool {
    if lhs.operate != rhs.operate {return false}
    if lhs.fifaMsg != rhs.fifaMsg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
