// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: update.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct protocol_notice_update_operate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///1bytes 事件id
  public var eventID: event_id = .null

  ///1bytes 具体事件键值
  public var eventKey: UInt32 = 0

  ///具体事件数值
  public var eventValue: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension protocol_notice_update_operate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "protocol_notice_update_operate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "event_id"),
    2: .standard(proto: "event_key"),
    3: .standard(proto: "event_value"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.eventID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.eventKey) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.eventValue) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.eventID != .null {
      try visitor.visitSingularEnumField(value: self.eventID, fieldNumber: 1)
    }
    if self.eventKey != 0 {
      try visitor.visitSingularUInt32Field(value: self.eventKey, fieldNumber: 2)
    }
    if self.eventValue != 0 {
      try visitor.visitSingularUInt32Field(value: self.eventValue, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: protocol_notice_update_operate, rhs: protocol_notice_update_operate) -> Bool {
    if lhs.eventID != rhs.eventID {return false}
    if lhs.eventKey != rhs.eventKey {return false}
    if lhs.eventValue != rhs.eventValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
